### ISSUE TITLE
How to use extension???

### ISSUE THREAD

**Issue by izzahkhan** [natchou/layout-trello#34]
I'm on my trello board page and when I click on the icon it just takes me to the chrome extension page and it doesn't actually let me use the extension.

**Comment by natalieperna** [comment]
Do you mean that it takes you back to the Chrome Web Store page for the extension? Is there any error message on the page, possibly in a yellow bar at the top?

The extension should work as shown in the animation below:

![List Layouts for Trello - How to](https://raw.githubusercontent.com/spellitwithaph/layout-trello/i26/screenshots/list_layouts_for_trello.gif)

**Comment by avemuru** [comment]
I have the same issue: take me back to Chrome Web Store page for extension. I see the icon is grayed out , maybe I need to sign in?

**Comment by natchou** [comment]
Does clicking the grey icon immediately send you to the Chrome web store page, or does it open a menu like this?

<img width="236" alt="screen shot 2017-08-27 at 10 41 43 am" src="https://user-images.githubusercontent.com/1953083/29752512-5e52b1e2-8b14-11e7-8cbf-f1cf06887d13.png">

And just to check, are you using Google Chrome as your browser? (It is possible to use Chrome extensions on some other web browsers, but this is known to cause bugs.)

**Comment by natchou** [comment]
Closing due to lack of communication. Please re-open if this issue persists.

**Comment by avemuru** [comment]
Got it to work - thanks

Regards,
Ajay Vemuru
408.332.9708

iPhone. iTypos. iApologize.

**Comment by zorabelle** [comment]
Hi @sudonatalie I'm having the same issue. I downloaded the zip and added this to my chrome but when I click on the icon it takes me back to the Chrome store webpage. My device and all is compatible. Could you please tell me how to make this work? 
Thank you

**Comment by patreids** [comment]
I had to close Chrome then reopen to get it to work, but I can't figure out how to get the grid option.
